prompt_gsm8k_van=[
    "Please generate five similar questions with integer answer in the following form Q1:{question}\n S1:{solution}\n A1:{answer}\n\n Q2:{question}\n S2:{solution}\n A2:{answer}\n\n Q3:{question}\n S3:{solution}\n A3:{answer}\n\n Q4:{question}\n S4:{solution}\n A4:{answer}\n\n Q5:{question}\n S5:{solution}\n A5:{answer}\n\n.",
    "Generate five similar questions with integer answer in the following form Q1:{question}\n S1:{solution}\n A1:{answer}\n\n Q2:{question}\n S2:{solution}\n A2:{answer}\n\n Q3:{question}\n S3:{solution}\n A3:{answer}\n\n Q4:{question}\n S4:{solution}\n A4:{answer}\n\n Q5:{question}\n S5:{solution}\n A5:{answer}\n\n.",

    "Please create five similar questions with integer answer in the following form Q1:{question}\n S1:{solution}\n A1:{answer}\n\n Q2:{question}\n S2:{solution}\n A2:{answer}\n\n Q3:{question}\n S3:{solution}\n A3:{answer}\n\n Q4:{question}\n S4:{solution}\n A4:{answer}\n\n Q5:{question}\n S5:{solution}\n A5:{answer}\n\n.",
    "Create five similar questions with integer answer in the following form Q1:{question}\n S1:{solution}\n A1:{answer}\n\n Q2:{question}\n S2:{solution}\n A2:{answer}\n\n Q3:{question}\n S3:{solution}\n A3:{answer}\n\n Q4:{question}\n S4:{solution}\n A4:{answer}\n\n Q5:{question}\n S5:{solution}\n A5:{answer}\n\n.",


    "Please output five similar questions with integer answer in the following form Q1:{question}\n S1:{solution}\n A1:{answer}\n\n Q2:{question}\n S2:{solution}\n A2:{answer}\n\n Q3:{question}\n S3:{solution}\n A3:{answer}\n\n Q4:{question}\n S4:{solution}\n A4:{answer}\n\n Q5:{question}\n S5:{solution}\n A5:{answer}\n\n.",
    "Output five similar questions with integer answer in the following form Q1:{question}\n S1:{solution}\n A1:{answer}\n\n Q2:{question}\n S2:{solution}\n A2:{answer}\n\n Q3:{question}\n S3:{solution}\n A3:{answer}\n\n Q4:{question}\n S4:{solution}\n A4:{answer}\n\n Q5:{question}\n S5:{solution}\n A5:{answer}\n\n.",
]

prompt_gsm8k_cot=["Please generate five similar questions with step by step reasoning process and an        integer answer in the following form Q1:{question}\n S1:{solution}\n A1:{answer}\n\n Q2:{question}\n S2:{solution}\n A2:{answer}\n\n Q3:{question}\n S3:{solution}\n A3:{answer}\n\n Q4:{question}\n S4:{solution}\n A4:{answer}\n\n Q5:{question}\n S5:{solution}\n A5:{answer}\n\n.",
"Generate five similar questions with step by step reasoning process and an integer answer in the following form Q1:{question}\n S1:{solution}\n A1:{answer}\n\n Q2:{question}\n S2:{solution}\n A2:{answer}\n\n Q3:{question}\n S3:{solution}\n A3:{answer}\n\n Q4:{question}\n S4:{solution}\n A4:{answer}\n\n Q5:{question}\n S5:{solution}\n A5:{answer}\n\n."
"Generate five similar questions with step by step reasoning process and an        integer answer in the following form Q1:{question}\n S1:{solution}\n A1:{answer}\n\n Q2:{question}\n S2:{solution}\n A2:{answer}\n\n Q3:{question}\n S3:{solution}\n A3:{answer}\n\n Q4:{question}\n S4:{solution}\n A4:{answer}\n\n Q5:{question}\n S5:{solution}\n A5:{answer}\n\n.",
"Generate five similar questions with step by step reasoning process and an integer answer in the following form Q1:{question}\n S1:{solution}\n A1:{answer}\n\n Q2:{question}\n S2:{solution}\n A2:{answer}\n\n Q3:{question}\n S3:{solution}\n A3:{answer}\n\n Q4:{question}\n S4:{solution}\n A4:{answer}\n\n Q5:{question}\n S5:{solution}\n A5:{answer}\n\n."



"Please create five similar questions with step by step reasoning process and an integer answer in the following form Q1:{question}\n S1:{solution}\n A1:{answer}\n\n Q2:{question}\n S2:{solution}\n A2:{answer}\n\n Q3:{question}\n S3:{solution}\n A3:{answer}\n\n Q4:{question}\n S4:{solution}\n A4:{answer}\n\n Q5:{question}\n S5:{solution}\n A5:{answer}\n\n.",
"Create five similar questions with step by step reasoning process and an integer answer in the following form Q1:{question}\n S1:{solution}\n A1:{answer}\n\n Q2:{question}\n S2:{solution}\n A2:{answer}\n\n Q3:{question}\n S3:{solution}\n A3:{answer}\n\n Q4:{question}\n S4:{solution}\n A4:{answer}\n\n Q5:{question}\n S5:{solution}\n A5:{answer}\n\n."
"Create five similar questions with step by step reasoning process and an integer answer in the following form Q1:{question}\n S1:{solution}\n A1:{answer}\n\n Q2:{question}\n S2:{solution}\n A2:{answer}\n\n Q3:{question}\n S3:{solution}\n A3:{answer}\n\n Q4:{question}\n S4:{solution}\n A4:{answer}\n\n Q5:{question}\n S5:{solution}\n A5:{answer}\n\n.",
"Create five similar questions with step by step reasoning process and an integer answer in the following form Q1:{question}\n S1:{solution}\n A1:{answer}\n\n Q2:{question}\n S2:{solution}\n A2:{answer}\n\n Q3:{question}\n S3:{solution}\n A3:{answer}\n\n Q4:{question}\n S4:{solution}\n A4:{answer}\n\n Q5:{question}\n S5:{solution}\n A5:{answer}\n\n."

"Please output five similar questions with step by step reasoning process and an integer answer in the following form Q1:{question}\n S1:{solution}\n A1:{answer}\n\n Q2:{question}\n S2:{solution}\n A2:{answer}\n\n Q3:{question}\n S3:{solution}\n A3:{answer}\n\n Q4:{question}\n S4:{solution}\n A4:{answer}\n\n Q5:{question}\n S5:{solution}\n A5:{answer}\n\n.",
"Output five similar questions with step by step reasoning process and an integer answer in the following form Q1:{question}\n S1:{solution}\n A1:{answer}\n\n Q2:{question}\n S2:{solution}\n A2:{answer}\n\n Q3:{question}\n S3:{solution}\n A3:{answer}\n\n Q4:{question}\n S4:{solution}\n A4:{answer}\n\n Q5:{question}\n S5:{solution}\n A5:{answer}\n\n."
"Output five similar questions with step by step reasoning process and an integer answer in the following form Q1:{question}\n S1:{solution}\n A1:{answer}\n\n Q2:{question}\n S2:{solution}\n A2:{answer}\n\n Q3:{question}\n S3:{solution}\n A3:{answer}\n\n Q4:{question}\n S4:{solution}\n A4:{answer}\n\n Q5:{question}\n S5:{solution}\n A5:{answer}\n\n.",
"Output five similar questions with step by step reasoning process and an integer answer in the following form Q1:{question}\n S1:{solution}\n A1:{answer}\n\n Q2:{question}\n S2:{solution}\n A2:{answer}\n\n Q3:{question}\n S3:{solution}\n A3:{answer}\n\n Q4:{question}\n S4:{solution}\n A4:{answer}\n\n Q5:{question}\n S5:{solution}\n A5:{answer}\n\n."
                  ]


prompt_arc_van=["Follwing the above question, generate five similar multiple choice science questions with  its choice labels, choice text and an answer label in the following form [[Question1:{question}\n Label1:[choice labels]\n Text1:[choice text]\n Ans1:{answer label}]]\n\n [[Question2:{question}\n Label2:[choice labels]\n Text2:[choice text]\n Ans2:{answer label}]]\n\n [[Question3:{question}\n Label3:[choice labels]\n Text3:[choice text]\n Ans3:{answer label}]]\n\n [[Question4:{question}\n Label4:[choice labels]\n Text4:[choice text]\n Ans4:{answer label}]]\n\n [[Question5:{question}\n Label5:[choice labels]\n Text5:[choice text]\n Ans5:{answer label}]]\n\n.",
    "Please Follwing the above question, generate five similar multiple choice science questions with its choice labels, choice text and an answer label in the following form [[Question1:{question}\n Label1:[choice labels]\n Text1:[choice text]\n Ans1:{answer label}]]\n\n [[Question2:{question}\n Label2:[choice labels]\n Text2:[choice text]\n Ans2:{answer label}]]\n\n [[Question3:{question}\n Label3:[choice labels]\n Text3:[choice text]\n Ans3:{answer label}]]\n\n [[Question4:{question}\n Label4:[choice labels]\n Text4:[choice text]\n Ans4:{answer label}]]\n\n [[Question5:{question}\n Label5:[choice labels]\n Text5:[choice text]\n Ans5:{answer label}]]\n\n.",
    
    "Follwing the above question, create five similar multiple choice science questions with  its choice labels, choice text and an answer label in the following form [[Question1:{question}\n Label1:[choice labels]\n Text1:[choice text]\n Ans1:{answer label}]]\n\n [[Question2:{question}\n Label2:[choice labels]\n Text2:[choice text]\n Ans2:{answer label}]]\n\n [[Question3:{question}\n Label3:[choice labels]\n Text3:[choice text]\n Ans3:{answer label}]]\n\n [[Question4:{question}\n Label4:[choice labels]\n Text4:[choice text]\n Ans4:{answer label}]]\n\n [[Question5:{question}\n Label5:[choice labels]\n Text5:[choice text]\n Ans5:{answer label}]]\n\n.",
    "Please Follwing the above question, create five similar multiple choice science questions with its choice labels, choice text and an answer label in the following form [[Question1:{question}\n Label1:[choice labels]\n Text1:[choice text]\n Ans1:{answer label}]]\n\n [[Question2:{question}\n Label2:[choice labels]\n Text2:[choice text]\n Ans2:{answer label}]]\n\n [[Question3:{question}\n Label3:[choice labels]\n Text3:[choice text]\n Ans3:{answer label}]]\n\n [[Question4:{question}\n Label4:[choice labels]\n Text4:[choice text]\n Ans4:{answer label}]]\n\n [[Question5:{question}\n Label5:[choice labels]\n Text5:[choice text]\n Ans5:{answer label}]]\n\n.",


    "Follwing the above question, output five similar multiple choice science questions with  its choice labels, choice text and an answer label in the following form [[Question1:{question}\n Label1:[choice labels]\n Text1:[choice text]\n Ans1:{answer label}]]\n\n [[Question2:{question}\n Label2:[choice labels]\n Text2:[choice text]\n Ans2:{answer label}]]\n\n [[Question3:{question}\n Label3:[choice labels]\n Text3:[choice text]\n Ans3:{answer label}]]\n\n [[Question4:{question}\n Label4:[choice labels]\n Text4:[choice text]\n Ans4:{answer label}]]\n\n [[Question5:{question}\n Label5:[choice labels]\n Text5:[choice text]\n Ans5:{answer label}]]\n\n.",
    "Please Follwing the above question, output five similar multiple choice science questions with its choice labels, choice text and an answer label in the following form [[Question1:{question}\n Label1:[choice labels]\n Text1:[choice text]\n Ans1:{answer label}]]\n\n [[Question2:{question}\n Label2:[choice labels]\n Text2:[choice text]\n Ans2:{answer label}]]\n\n [[Question3:{question}\n Label3:[choice labels]\n Text3:[choice text]\n Ans3:{answer label}]]\n\n [[Question4:{question}\n Label4:[choice labels]\n Text4:[choice text]\n Ans4:{answer label}]]\n\n [[Question5:{question}\n Label5:[choice labels]\n Text5:[choice text]\n Ans5:{answer label}]]\n\n."]




prompt_arc_cot=["Follwing the above question, generate five similar multiple choice science questions with its choice labels, choice text, the explanation of the right answer and an answer label in the following form [[Question1:{question}\n Label1:[choice labels]\n Text1:[choice text]\n Sol1:{the explanation of the right answer}\n Ans1:{answer label}]]\n\n [[Question2:{question}\n Label2:[choice labels]\n Text2:[choice text]\n Sol2:{the explanation of the right answer}\n Ans2:{answer label}]]\n\n [[Question3:{question}\n Label3:[choice labels]\n Text3:[choice text]\n Sol3:{the explanation of the right answer}\n Ans3:{answer label}]]\n\n [[Question4:{question}\n Label4:[choice labels]\n Text4:[choice text]\n Sol4:{the explanation of the right answer}\n Ans4:{answer label}]]\n\n [[Question5:{question}\n Label5:[choice labels]\n Text5:[choice text]\n Sol5:{the explanation of the right answer}\n Ans5:{answer label}]]\n\n  [[Question6:{question}\n Label6:[choice labels]\n Text6:[choice text]\n Sol6:{the explanation of the right answer}\n Ans6:{answer label}]]\n\n [[Question7:{question}\n Label7:[choice labels]\n Text7:[choice text]\n Sol7:{the explanation of the right answer}\n Ans7:{answer label}]]\n\n [[Question8:{question}\n Label8:[choice labels]\n Text8:[choice text]\n Sol8:{the explanation of the right answer}\n Ans8:{answer label}]]\n\n [[Question9:{question}\n Label9:[choice labels]\n Text9:[choice text]\n Sol9:{the explanation of the right answer}\n Ans9:{answer label}]]\n\n [[Question10:{question}\n Label10:[choice labels]\n Text10:[choice text]\n Sol10:{the explanation of the right answer}\n Ans10:{answer label}]]\n\n.",
    "Please follwing the above question, generate five similar multiple choice science questions with its choice labels, choice text, the explanation of the right answer and an answer label in the following form [[Question1:{question}\n Label1:[choice labels]\n Text1:[choice text]\n Sol1:{the explanation of the right answer}\n Ans1:{answer label}]]\n\n [[Question2:{question}\n Label2:[choice labels]\n Text2:[choice text]\n Sol2:{the explanation of the right answer}\n Ans2:{answer label}]]\n\n [[Question3:{question}\n Label3:[choice labels]\n Text3:[choice text]\n Sol3:{the explanation of the right answer}\n Ans3:{answer label}]]\n\n [[Question4:{question}\n Label4:[choice labels]\n Text4:[choice text]\n Sol4:{the explanation of the right answer}\n Ans4:{answer label}]]\n\n [[Question5:{question}\n Label5:[choice labels]\n Text5:[choice text]\n Sol5:{the explanation of the right answer}\n Ans5:{answer label}]]\n\n  [[Question6:{question}\n Label6:[choice labels]\n Text6:[choice text]\n Sol6:{the explanation of the right answer}\n Ans6:{answer label}]]\n\n [[Question7:{question}\n Label7:[choice labels]\n Text7:[choice text]\n Sol7:{the explanation of the right answer}\n Ans7:{answer label}]]\n\n [[Question8:{question}\n Label8:[choice labels]\n Text8:[choice text]\n Sol8:{the explanation of the right answer}\n Ans8:{answer label}]]\n\n [[Question9:{question}\n Label9:[choice labels]\n Text9:[choice text]\n Sol9:{the explanation of the right answer}\n Ans9:{answer label}]]\n\n [[Question10:{question}\n Label10:[choice labels]\n Text10:[choice text]\n Sol10:{the explanation of the right answer}\n Ans10:{answer label}]]\n\n.",
    
    
    "Follwing the above question, create five similar multiple choice science questions with its choice labels, choice text, the explanation of the right answer and an answer label in the following form [[Question1:{question}\n Label1:[choice labels]\n Text1:[choice text]\n Sol1:{the explanation of the right answer}\n Ans1:{answer label}]]\n\n [[Question2:{question}\n Label2:[choice labels]\n Text2:[choice text]\n Sol2:{the explanation of the right answer}\n Ans2:{answer label}]]\n\n [[Question3:{question}\n Label3:[choice labels]\n Text3:[choice text]\n Sol3:{the explanation of the right answer}\n Ans3:{answer label}]]\n\n [[Question4:{question}\n Label4:[choice labels]\n Text4:[choice text]\n Sol4:{the explanation of the right answer}\n Ans4:{answer label}]]\n\n [[Question5:{question}\n Label5:[choice labels]\n Text5:[choice text]\n Sol5:{the explanation of the right answer}\n Ans5:{answer label}]]\n\n  [[Question6:{question}\n Label6:[choice labels]\n Text6:[choice text]\n Sol6:{the explanation of the right answer}\n Ans6:{answer label}]]\n\n [[Question7:{question}\n Label7:[choice labels]\n Text7:[choice text]\n Sol7:{the explanation of the right answer}\n Ans7:{answer label}]]\n\n [[Question8:{question}\n Label8:[choice labels]\n Text8:[choice text]\n Sol8:{the explanation of the right answer}\n Ans8:{answer label}]]\n\n [[Question9:{question}\n Label9:[choice labels]\n Text9:[choice text]\n Sol9:{the explanation of the right answer}\n Ans9:{answer label}]]\n\n [[Question10:{question}\n Label10:[choice labels]\n Text10:[choice text]\n Sol10:{the explanation of the right answer}\n Ans10:{answer label}]]\n\n.",
    "Please follwing the above question, create five similar multiple choice science questions with its choice labels, choice text, the explanation of the right answer and an answer label in the following form [[Question1:{question}\n Label1:[choice labels]\n Text1:[choice text]\n Sol1:{the explanation of the right answer}\n Ans1:{answer label}]]\n\n [[Question2:{question}\n Label2:[choice labels]\n Text2:[choice text]\n Sol2:{the explanation of the right answer}\n Ans2:{answer label}]]\n\n [[Question3:{question}\n Label3:[choice labels]\n Text3:[choice text]\n Sol3:{the explanation of the right answer}\n Ans3:{answer label}]]\n\n [[Question4:{question}\n Label4:[choice labels]\n Text4:[choice text]\n Sol4:{the explanation of the right answer}\n Ans4:{answer label}]]\n\n [[Question5:{question}\n Label5:[choice labels]\n Text5:[choice text]\n Sol5:{the explanation of the right answer}\n Ans5:{answer label}]]\n\n  [[Question6:{question}\n Label6:[choice labels]\n Text6:[choice text]\n Sol6:{the explanation of the right answer}\n Ans6:{answer label}]]\n\n [[Question7:{question}\n Label7:[choice labels]\n Text7:[choice text]\n Sol7:{the explanation of the right answer}\n Ans7:{answer label}]]\n\n [[Question8:{question}\n Label8:[choice labels]\n Text8:[choice text]\n Sol8:{the explanation of the right answer}\n Ans8:{answer label}]]\n\n [[Question9:{question}\n Label9:[choice labels]\n Text9:[choice text]\n Sol9:{the explanation of the right answer}\n Ans9:{answer label}]]\n\n [[Question10:{question}\n Label10:[choice labels]\n Text10:[choice text]\n Sol10:{the explanation of the right answer}\n Ans10:{answer label}]]\n\n.",
    
    
    
    "Follwing the above question, output five similar multiple choice science questions with its choice labels, choice text, the explanation of the right answer and an answer label in the following form [[Question1:{question}\n Label1:[choice labels]\n Text1:[choice text]\n Sol1:{the explanation of the right answer}\n Ans1:{answer label}]]\n\n [[Question2:{question}\n Label2:[choice labels]\n Text2:[choice text]\n Sol2:{the explanation of the right answer}\n Ans2:{answer label}]]\n\n [[Question3:{question}\n Label3:[choice labels]\n Text3:[choice text]\n Sol3:{the explanation of the right answer}\n Ans3:{answer label}]]\n\n [[Question4:{question}\n Label4:[choice labels]\n Text4:[choice text]\n Sol4:{the explanation of the right answer}\n Ans4:{answer label}]]\n\n [[Question5:{question}\n Label5:[choice labels]\n Text5:[choice text]\n Sol5:{the explanation of the right answer}\n Ans5:{answer label}]]\n\n  [[Question6:{question}\n Label6:[choice labels]\n Text6:[choice text]\n Sol6:{the explanation of the right answer}\n Ans6:{answer label}]]\n\n [[Question7:{question}\n Label7:[choice labels]\n Text7:[choice text]\n Sol7:{the explanation of the right answer}\n Ans7:{answer label}]]\n\n [[Question8:{question}\n Label8:[choice labels]\n Text8:[choice text]\n Sol8:{the explanation of the right answer}\n Ans8:{answer label}]]\n\n [[Question9:{question}\n Label9:[choice labels]\n Text9:[choice text]\n Sol9:{the explanation of the right answer}\n Ans9:{answer label}]]\n\n [[Question10:{question}\n Label10:[choice labels]\n Text10:[choice text]\n Sol10:{the explanation of the right answer}\n Ans10:{answer label}]]\n\n.",
    "Please follwing the above question, output five similar multiple choice science questions with its choice labels, choice text, the explanation of the right answer and an answer label in the following form [[Question1:{question}\n Label1:[choice labels]\n Text1:[choice text]\n Sol1:{the explanation of the right answer}\n Ans1:{answer label}]]\n\n [[Question2:{question}\n Label2:[choice labels]\n Text2:[choice text]\n Sol2:{the explanation of the right answer}\n Ans2:{answer label}]]\n\n [[Question3:{question}\n Label3:[choice labels]\n Text3:[choice text]\n Sol3:{the explanation of the right answer}\n Ans3:{answer label}]]\n\n [[Question4:{question}\n Label4:[choice labels]\n Text4:[choice text]\n Sol4:{the explanation of the right answer}\n Ans4:{answer label}]]\n\n [[Question5:{question}\n Label5:[choice labels]\n Text5:[choice text]\n Sol5:{the explanation of the right answer}\n Ans5:{answer label}]]\n\n  [[Question6:{question}\n Label6:[choice labels]\n Text6:[choice text]\n Sol6:{the explanation of the right answer}\n Ans6:{answer label}]]\n\n [[Question7:{question}\n Label7:[choice labels]\n Text7:[choice text]\n Sol7:{the explanation of the right answer}\n Ans7:{answer label}]]\n\n [[Question8:{question}\n Label8:[choice labels]\n Text8:[choice text]\n Sol8:{the explanation of the right answer}\n Ans8:{answer label}]]\n\n [[Question9:{question}\n Label9:[choice labels]\n Text9:[choice text]\n Sol9:{the explanation of the right answer}\n Ans9:{answer label}]]\n\n [[Question10:{question}\n Label10:[choice labels]\n Text10:[choice text]\n Sol10:{the explanation of the right answer}\n Ans10:{answer label}]]\n\n."]



prompt_math_van=[
    '\nPlease follwing the above question, generate five similar questions with its answer in Latex. Please output in the following form [[Question1:{question}\n Answer1:$answer in Latex$]]\n\n [[Question2:{question}\n Answer2:$answer in Latex$]]\n\n [[Question3:{question}\n Answer3:$answer in Latex$]]\n\n [[Question4:{question}\n Answer4:$answer in Latex$]]\n\n [[Question5:{question}\n Answer5:$answer in Latex$]]\n\n.',
    '\nFollwing the above question, generate five similar questions with its answer in Latex. Please output in the following form [[Question1:{question}\n Answer1:$answer in Latex$]]\n\n [[Question2:{question}\n Answer2:$answer in Latex$]]\n\n [[Question3:{question}\n Answer3:$answer in Latex$]]\n\n [[Question4:{question}\n Answer4:$answer in Latex$]]\n\n [[Question5:{question}\n Answer5:$answer in Latex$]]\n\n.',


    '\nPlease follwing the above question, create five similar questions with its answer in Latex. Please output in the following form [[Question1:{question}\n Answer1:$answer in Latex$]]\n\n [[Question2:{question}\n Answer2:$answer in Latex$]]\n\n [[Question3:{question}\n Answer3:$answer in Latex$]]\n\n [[Question4:{question}\n Answer4:$answer in Latex$]]\n\n [[Question5:{question}\n Answer5:$answer in Latex$]]\n\n.',
    '\nFollwing the above question, create five similar questions with its answer in Latex. Please output in the following form [[Question1:{question}\n Answer1:$answer in Latex$]]\n\n [[Question2:{question}\n Answer2:$answer in Latex$]]\n\n [[Question3:{question}\n Answer3:$answer in Latex$]]\n\n [[Question4:{question}\n Answer4:$answer in Latex$]]\n\n [[Question5:{question}\n Answer5:$answer in Latex$]]\n\n.',


    '\nPlease follwing the above question, output five similar questions with its answer in Latex. Please output in the following form [[Question1:{question}\n Answer1:$answer in Latex$]]\n\n [[Question2:{question}\n Answer2:$answer in Latex$]]\n\n [[Question3:{question}\n Answer3:$answer in Latex$]]\n\n [[Question4:{question}\n Answer4:$answer in Latex$]]\n\n [[Question5:{question}\n Answer5:$answer in Latex$]]\n\n.',
    '\nFollwing the above question, output five similar questions with its answer in Latex. Please output in the following form [[Question1:{question}\n Answer1:$answer in Latex$]]\n\n [[Question2:{question}\n Answer2:$answer in Latex$]]\n\n [[Question3:{question}\n Answer3:$answer in Latex$]]\n\n [[Question4:{question}\n Answer4:$answer in Latex$]]\n\n [[Question5:{question}\n Answer5:$answer in Latex$]]\n\n.'
]


prompt_math_cot=['\nPlease follwing the above question, generate 5 similar questions with its step by step solution and answer in Latex. Please output in the following form [[Question1:{question}\n Sol1:[step by step solution]\n Answer1:$answer in Latex$]]\n\n [[Question2:{question}\n Sol2:[step by step solution]\n Answer2:$answer in Latex$]]\n\n [[Question3:{question}\n Sol3:[step by step solution]\n Answer3:$answer in Latex$]]\n\n [[Question4:{question}\n Sol4:[step by step solution]\n Answer4:$answer in Latex$]]\n\n [[Question5:{question}\n Sol5:[step by step solution]\n Answer5:$answer in Latex$]]\n\n.',
    '\nPlease follwing the above question, generate 5 similar questions with its step by step solution and answer in Latex. Please output in the following form [[Question1:{question}\n Sol1:[step by step solution]\n Answer1:$answer in Latex$]]\n\n [[Question2:{question}\n Sol2:[step by step solution]\n Answer2:$answer in Latex$]]\n\n [[Question3:{question}\n Sol3:[step by step solution]\n Answer3:$answer in Latex$]]\n\n [[Question4:{question}\n Sol4:[step by step solution]\n Answer4:$answer in Latex$]]\n\n [[Question5:{question}\n Sol5:[step by step solution]\n Answer5:$answer in Latex$]]\n\n.',
    
    
    
    '\nPlease follwing the above question, create 5 similar questions with its step by step solution and answer in Latex. Please output in the following form [[Question1:{question}\n Sol1:[step by step solution]\n Answer1:$answer in Latex$]]\n\n [[Question2:{question}\n Sol2:[step by step solution]\n Answer2:$answer in Latex$]]\n\n [[Question3:{question}\n Sol3:[step by step solution]\n Answer3:$answer in Latex$]]\n\n [[Question4:{question}\n Sol4:[step by step solution]\n Answer4:$answer in Latex$]]\n\n [[Question5:{question}\n Sol5:[step by step solution]\n Answer5:$answer in Latex$]]\n\n.',
    '\nPlease follwing the above question, create 5 similar questions with its step by step solution and answer in Latex. Please output in the following form [[Question1:{question}\n Sol1:[step by step solution]\n Answer1:$answer in Latex$]]\n\n [[Question2:{question}\n Sol2:[step by step solution]\n Answer2:$answer in Latex$]]\n\n [[Question3:{question}\n Sol3:[step by step solution]\n Answer3:$answer in Latex$]]\n\n [[Question4:{question}\n Sol4:[step by step solution]\n Answer4:$answer in Latex$]]\n\n [[Question5:{question}\n Sol5:[step by step solution]\n Answer5:$answer in Latex$]]\n\n.',
    
    
    '\nPlease follwing the above question, output 5 similar questions with its step by step solution and answer in Latex. Please output in the following form [[Question1:{question}\n Sol1:[step by step solution]\n Answer1:$answer in Latex$]]\n\n [[Question2:{question}\n Sol2:[step by step solution]\n Answer2:$answer in Latex$]]\n\n [[Question3:{question}\n Sol3:[step by step solution]\n Answer3:$answer in Latex$]]\n\n [[Question4:{question}\n Sol4:[step by step solution]\n Answer4:$answer in Latex$]]\n\n [[Question5:{question}\n Sol5:[step by step solution]\n Answer5:$answer in Latex$]]\n\n.',
    '\nPlease follwing the above question, output 5 similar questions with its step by step solution and answer in Latex. Please output in the following form [[Question1:{question}\n Sol1:[step by step solution]\n Answer1:$answer in Latex$]]\n\n [[Question2:{question}\n Sol2:[step by step solution]\n Answer2:$answer in Latex$]]\n\n [[Question3:{question}\n Sol3:[step by step solution]\n Answer3:$answer in Latex$]]\n\n [[Question4:{question}\n Sol4:[step by step solution]\n Answer4:$answer in Latex$]]\n\n [[Question5:{question}\n Sol5:[step by step solution]\n Answer5:$answer in Latex$]]\n\n.']


prompt_mmlu_van=["Please follwing the above question, generate five similar multiple choice {} questions with its choice labels, choice text and an answer label (A or B or C or D). Note that each question should be complete and can be answered independently. Please output in the following form [[Question1:[question]\n Label1:[choice labels]\n Text1:[choice text]\n Ans1:[A or B or C or D]]]\n\n [[Question2:[question]\n Label2:[choice labels]\n Text2:[choice text]\n Ans2:[A or B or C or D]]]\n\n [[Question3:[question]\n Label3:[choice labels]\n Text3:[choice text]\n Ans3:[A or B or C or D]]]\n\n [[Question4:[question]\n Label4:[choice labels]\n Text4:[choice text]\n Ans4:[A or B or C or D]]]\n\n [[Question5:[question]\n Label5:[choice labels]\n Text5:[choice text]\n Ans5:[A or B or C or D]]]\n\n.",
    "Follwing the above question, generate five similar multiple choice {} questions with its choice labels, choice text and an answer label (A or B or C or D). Note that each question should be complete and can be answered independently. Please output in the following form [[Question1:[question]\n Label1:[choice labels]\n Text1:[choice text]\n Ans1:[A or B or C or D]]]\n\n [[Question2:[question]\n Label2:[choice labels]\n Text2:[choice text]\n Ans2:[A or B or C or D]]]\n\n [[Question3:[question]\n Label3:[choice labels]\n Text3:[choice text]\n Ans3:[A or B or C or D]]]\n\n [[Question4:[question]\n Label4:[choice labels]\n Text4:[choice text]\n Ans4:[A or B or C or D]]]\n\n [[Question5:[question]\n Label5:[choice labels]\n Text5:[choice text]\n Ans5:[A or B or C or D]]]\n\n.",
    
    
    "Please follwing the above question, create five similar multiple choice {} questions with its choice labels, choice text and an answer label (A or B or C or D). Note that each question should be complete and can be answered independently. Please output in the following form [[Question1:[question]\n Label1:[choice labels]\n Text1:[choice text]\n Ans1:[A or B or C or D]]]\n\n [[Question2:[question]\n Label2:[choice labels]\n Text2:[choice text]\n Ans2:[A or B or C or D]]]\n\n [[Question3:[question]\n Label3:[choice labels]\n Text3:[choice text]\n Ans3:[A or B or C or D]]]\n\n [[Question4:[question]\n Label4:[choice labels]\n Text4:[choice text]\n Ans4:[A or B or C or D]]]\n\n [[Question5:[question]\n Label5:[choice labels]\n Text5:[choice text]\n Ans5:[A or B or C or D]]]\n\n.",
    "Follwing the above question, create five similar multiple choice {} questions with its choice labels, choice text and an answer label (A or B or C or D). Note that each question should be complete and can be answered independently. Please output in the following form [[Question1:[question]\n Label1:[choice labels]\n Text1:[choice text]\n Ans1:[A or B or C or D]]]\n\n [[Question2:[question]\n Label2:[choice labels]\n Text2:[choice text]\n Ans2:[A or B or C or D]]]\n\n [[Question3:[question]\n Label3:[choice labels]\n Text3:[choice text]\n Ans3:[A or B or C or D]]]\n\n [[Question4:[question]\n Label4:[choice labels]\n Text4:[choice text]\n Ans4:[A or B or C or D]]]\n\n [[Question5:[question]\n Label5:[choice labels]\n Text5:[choice text]\n Ans5:[A or B or C or D]]]\n\n.",
    
    
    "Please follwing the above question, output five similar multiple choice {} questions with its choice labels, choice text and an answer label (A or B or C or D). Note that each question should be complete and can be answered independently. Please output in the following form [[Question1:[question]\n Label1:[choice labels]\n Text1:[choice text]\n Ans1:[A or B or C or D]]]\n\n [[Question2:[question]\n Label2:[choice labels]\n Text2:[choice text]\n Ans2:[A or B or C or D]]]\n\n [[Question3:[question]\n Label3:[choice labels]\n Text3:[choice text]\n Ans3:[A or B or C or D]]]\n\n [[Question4:[question]\n Label4:[choice labels]\n Text4:[choice text]\n Ans4:[A or B or C or D]]]\n\n [[Question5:[question]\n Label5:[choice labels]\n Text5:[choice text]\n Ans5:[A or B or C or D]]]\n\n.",
    "Follwing the above question, output five similar multiple choice {} questions with its choice labels, choice text and an answer label (A or B or C or D). Note that each question should be complete and can be answered independently. Please output in the following form [[Question1:[question]\n Label1:[choice labels]\n Text1:[choice text]\n Ans1:[A or B or C or D]]]\n\n [[Question2:[question]\n Label2:[choice labels]\n Text2:[choice text]\n Ans2:[A or B or C or D]]]\n\n [[Question3:[question]\n Label3:[choice labels]\n Text3:[choice text]\n Ans3:[A or B or C or D]]]\n\n [[Question4:[question]\n Label4:[choice labels]\n Text4:[choice text]\n Ans4:[A or B or C or D]]]\n\n [[Question5:[question]\n Label5:[choice labels]\n Text5:[choice text]\n Ans5:[A or B or C or D]]]\n\n."]

prompt_mmlu_cot=["Follwing the above question, generate five similar multiple choice {} questions with its choice labels, choice text, the step by step reason to choose your answer and an answer label (A or B or C or D). Note that each question should be complete and can be answered independently. Please output in the following form [[Question1:[question]\n Label1:[choice labels]\n Text1:[choice text]\n Sol1:[reason to choose your answer]\n Ans1:[A or B or C or D]]]\n\n [[Question2:[question]\n Label2:[choice labels]\n Text2:[choice text]\n Sol2:[reason to choose your answer]\n Ans2:[A or B or C or D]]]\n\n [[Question3:[question]\n Label3:[choice labels]\n Text3:[choice text]\n Sol3:[reason to choose your answer]\n Ans3:[A or B or C or D]]]\n\n [[Question4:[question]\n Label4:[choice labels]\n Text4:[choice text]\n Sol4:[reason to choose your answer]\n Ans4:[A or B or C or D]]]\n\n [[Question5:[question]\n Label5:[choice labels]\n Text5:[choice text]\n Sol5:[reason to choose your answer]\n Ans5:[A or B or C or D]]]\n\n.",
    "Please follwing the above question, generate five similar multiple choice {} questions with its choice labels, choice text, the step by step reason to choose your answer and an answer label (A or B or C or D). Note that each question should be complete and can be answered independently. Please output in the following form [[Question1:[question]\n Label1:[choice labels]\n Text1:[choice text]\n Sol1:[reason to choose your answer]\n Ans1:[A or B or C or D]]]\n\n [[Question2:[question]\n Label2:[choice labels]\n Text2:[choice text]\n Sol2:[reason to choose your answer]\n Ans2:[A or B or C or D]]]\n\n [[Question3:[question]\n Label3:[choice labels]\n Text3:[choice text]\n Sol3:[reason to choose your answer]\n Ans3:[A or B or C or D]]]\n\n [[Question4:[question]\n Label4:[choice labels]\n Text4:[choice text]\n Sol4:[reason to choose your answer]\n Ans4:[A or B or C or D]]]\n\n [[Question5:[question]\n Label5:[choice labels]\n Text5:[choice text]\n Sol5:[reason to choose your answer]\n Ans5:[A or B or C or D]]]\n\n.",
    
    
    "Follwing the above question, create five similar multiple choice {} questions with its choice labels, choice text, the step by step reason to choose your answer and an answer label (A or B or C or D). Note that each question should be complete and can be answered independently. Please output in the following form [[Question1:[question]\n Label1:[choice labels]\n Text1:[choice text]\n Sol1:[reason to choose your answer]\n Ans1:[A or B or C or D]]]\n\n [[Question2:[question]\n Label2:[choice labels]\n Text2:[choice text]\n Sol2:[reason to choose your answer]\n Ans2:[A or B or C or D]]]\n\n [[Question3:[question]\n Label3:[choice labels]\n Text3:[choice text]\n Sol3:[reason to choose your answer]\n Ans3:[A or B or C or D]]]\n\n [[Question4:[question]\n Label4:[choice labels]\n Text4:[choice text]\n Sol4:[reason to choose your answer]\n Ans4:[A or B or C or D]]]\n\n [[Question5:[question]\n Label5:[choice labels]\n Text5:[choice text]\n Sol5:[reason to choose your answer]\n Ans5:[A or B or C or D]]]\n\n.",
    "Please follwing the above question, create five similar multiple choice {} questions with its choice labels, choice text, the step by step reason to choose your answer and an answer label (A or B or C or D). Note that each question should be complete and can be answered independently. Please output in the following form [[Question1:[question]\n Label1:[choice labels]\n Text1:[choice text]\n Sol1:[reason to choose your answer]\n Ans1:[A or B or C or D]]]\n\n [[Question2:[question]\n Label2:[choice labels]\n Text2:[choice text]\n Sol2:[reason to choose your answer]\n Ans2:[A or B or C or D]]]\n\n [[Question3:[question]\n Label3:[choice labels]\n Text3:[choice text]\n Sol3:[reason to choose your answer]\n Ans3:[A or B or C or D]]]\n\n [[Question4:[question]\n Label4:[choice labels]\n Text4:[choice text]\n Sol4:[reason to choose your answer]\n Ans4:[A or B or C or D]]]\n\n [[Question5:[question]\n Label5:[choice labels]\n Text5:[choice text]\n Sol5:[reason to choose your answer]\n Ans5:[A or B or C or D]]]\n\n.",
    
    
    "Follwing the above question, output five similar multiple choice {} questions with its choice labels, choice text, the step by step reason to choose your answer and an answer label (A or B or C or D). Note that each question should be complete and can be answered independently. Please output in the following form [[Question1:[question]\n Label1:[choice labels]\n Text1:[choice text]\n Sol1:[reason to choose your answer]\n Ans1:[A or B or C or D]]]\n\n [[Question2:[question]\n Label2:[choice labels]\n Text2:[choice text]\n Sol2:[reason to choose your answer]\n Ans2:[A or B or C or D]]]\n\n [[Question3:[question]\n Label3:[choice labels]\n Text3:[choice text]\n Sol3:[reason to choose your answer]\n Ans3:[A or B or C or D]]]\n\n [[Question4:[question]\n Label4:[choice labels]\n Text4:[choice text]\n Sol4:[reason to choose your answer]\n Ans4:[A or B or C or D]]]\n\n [[Question5:[question]\n Label5:[choice labels]\n Text5:[choice text]\n Sol5:[reason to choose your answer]\n Ans5:[A or B or C or D]]]\n\n.",
    "Please follwing the above question, output five similar multiple choice {} questions with its choice labels, choice text, the step by step reason to choose your answer and an answer label (A or B or C or D). Note that each question should be complete and can be answered independently. Please output in the following form [[Question1:[question]\n Label1:[choice labels]\n Text1:[choice text]\n Sol1:[reason to choose your answer]\n Ans1:[A or B or C or D]]]\n\n [[Question2:[question]\n Label2:[choice labels]\n Text2:[choice text]\n Sol2:[reason to choose your answer]\n Ans2:[A or B or C or D]]]\n\n [[Question3:[question]\n Label3:[choice labels]\n Text3:[choice text]\n Sol3:[reason to choose your answer]\n Ans3:[A or B or C or D]]]\n\n [[Question4:[question]\n Label4:[choice labels]\n Text4:[choice text]\n Sol4:[reason to choose your answer]\n Ans4:[A or B or C or D]]]\n\n [[Question5:[question]\n Label5:[choice labels]\n Text5:[choice text]\n Sol5:[reason to choose your answer]\n Ans5:[A or B or C or D]]]\n\n.",]


prompt_ceval_van=['请模仿上面的问题，生成5个相似的关于{}考试的单项选择题，和这个这个题目的选项标签，选项内容和答案。每个问题必须是完整且能被独立回答的。请以以下格式输出答案：[[题目1:[题目]\n 选项标签1:[选项标签]\n 选项内容1:[选项内容]\n 答案1:[A或B或C或D]]]\n\n [[题目2:[题目]\n 选项标签2:[选项标签]\n 选项内容2:[选项内容]\n 答案2:[A或B或C或D]]]\n\n [[题目3:[题目]\n 选项标签3:[选项标签]\n 选项内容3:[选项内容]\n 答案3:[A或B或C或D]]]\n\n [[题目4:[题目]\n 选项标签4:[选项标签]\n 选项内容4:[选项内容]\n 答案4:[A或B或C或D]]]\n\n [[题目5:[题目]\n 选项标签5:[选项标签]\n 选项内容5:[选项内容]\n 答案5:[A或B或C或D]]]。',
    '模仿上面的问题，生成5个相似的关于{}考试的单项选择题，和这个这个题目的选项标签，选项内容和答案。每个问题必须是完整且能被独立回答的。请以以下格式输出答案：[[题目1:[题目]\n 选项标签1:[选项标签]\n 选项内容1:[选项内容]\n 答案1:[A或B或C或D]]]\n\n [[题目2:[题目]\n 选项标签2:[选项标签]\n 选项内容2:[选项内容]\n 答案2:[A或B或C或D]]]\n\n [[题目3:[题目]\n 选项标签3:[选项标签]\n 选项内容3:[选项内容]\n 答案3:[A或B或C或D]]]\n\n [[题目4:[题目]\n 选项标签4:[选项标签]\n 选项内容4:[选项内容]\n 答案4:[A或B或C或D]]]\n\n [[题目5:[题目]\n 选项标签5:[选项标签]\n 选项内容5:[选项内容]\n 答案5:[A或B或C或D]]]。',
    
    
    '请模仿上面的问题，输出5个相似的关于{}考试的单项选择题，和这个这个题目的选项标签，选项内容和答案。每个问题必须是完整且能被独立回答的。请以以下格式输出答案：[[题目1:[题目]\n 选项标签1:[选项标签]\n 选项内容1:[选项内容]\n 答案1:[A或B或C或D]]]\n\n [[题目2:[题目]\n 选项标签2:[选项标签]\n 选项内容2:[选项内容]\n 答案2:[A或B或C或D]]]\n\n [[题目3:[题目]\n 选项标签3:[选项标签]\n 选项内容3:[选项内容]\n 答案3:[A或B或C或D]]]\n\n [[题目4:[题目]\n 选项标签4:[选项标签]\n 选项内容4:[选项内容]\n 答案4:[A或B或C或D]]]\n\n [[题目5:[题目]\n 选项标签5:[选项标签]\n 选项内容5:[选项内容]\n 答案5:[A或B或C或D]]]。',
    '模仿上面的问题，输出5个相似的关于{}考试的单项选择题，和这个这个题目的选项标签，选项内容和答案。每个问题必须是完整且能被独立回答的。请以以下格式输出答案：[[题目1:[题目]\n 选项标签1:[选项标签]\n 选项内容1:[选项内容]\n 答案1:[A或B或C或D]]]\n\n [[题目2:[题目]\n 选项标签2:[选项标签]\n 选项内容2:[选项内容]\n 答案2:[A或B或C或D]]]\n\n [[题目3:[题目]\n 选项标签3:[选项标签]\n 选项内容3:[选项内容]\n 答案3:[A或B或C或D]]]\n\n [[题目4:[题目]\n 选项标签4:[选项标签]\n 选项内容4:[选项内容]\n 答案4:[A或B或C或D]]]\n\n [[题目5:[题目]\n 选项标签5:[选项标签]\n 选项内容5:[选项内容]\n 答案5:[A或B或C或D]]]。',
    
    '请模仿上面的问题，构造5个相似的关于{}考试的单项选择题，和这个这个题目的选项标签，选项内容和答案。每个问题必须是完整且能被独立回答的。请以以下格式输出答案：[[题目1:[题目]\n 选项标签1:[选项标签]\n 选项内容1:[选项内容]\n 答案1:[A或B或C或D]]]\n\n [[题目2:[题目]\n 选项标签2:[选项标签]\n 选项内容2:[选项内容]\n 答案2:[A或B或C或D]]]\n\n [[题目3:[题目]\n 选项标签3:[选项标签]\n 选项内容3:[选项内容]\n 答案3:[A或B或C或D]]]\n\n [[题目4:[题目]\n 选项标签4:[选项标签]\n 选项内容4:[选项内容]\n 答案4:[A或B或C或D]]]\n\n [[题目5:[题目]\n 选项标签5:[选项标签]\n 选项内容5:[选项内容]\n 答案5:[A或B或C或D]]]。',
    '模仿上面的问题，构造5个相似的关于{}考试的单项选择题，和这个这个题目的选项标签，选项内容和答案。每个问题必须是完整且能被独立回答的。请以以下格式输出答案：[[题目1:[题目]\n 选项标签1:[选项标签]\n 选项内容1:[选项内容]\n 答案1:[A或B或C或D]]]\n\n [[题目2:[题目]\n 选项标签2:[选项标签]\n 选项内容2:[选项内容]\n 答案2:[A或B或C或D]]]\n\n [[题目3:[题目]\n 选项标签3:[选项标签]\n 选项内容3:[选项内容]\n 答案3:[A或B或C或D]]]\n\n [[题目4:[题目]\n 选项标签4:[选项标签]\n 选项内容4:[选项内容]\n 答案4:[A或B或C或D]]]\n\n [[题目5:[题目]\n 选项标签5:[选项标签]\n 选项内容5:[选项内容]\n 答案5:[A或B或C或D]]]。',]


prompt_ceval_cot=['请模仿上面的问题，生成5个相似的关于{}考试的单项选择题，和这个这个题目的选项标签，选项内容，逐步的推导出答案的过程和正确答案。每个问题必须是完整且能被独立回答的。请以以下格式输出答案：[[题目1:[题目]\n 选项标签1:[选项标签]\n 选项内容1:[选项内容]\n 解析1：[逐步的推导出答案的过程]\n 答案1:[A或B或C或D]]]\n\n [[题目2:[题目]\n 选项标签2:[选项标签]\n 选项内容2:[选项内容]\n 解析2：[逐步的推导出答案的过程]\n 答案2:[A或B或C或D]]]\n\n [[题目3:[题目]\n 选项标签3:[选项标签]\n 选项内容3:[选项内容]\n 解析3：[逐步的推导出答案的过程]\n 答案3:[A或B或C或D]]]\n\n [[题目4:[题目]\n 选项标签4:[选项标签]\n 选项内容4:[选项内容]\n 解析4：[逐步的推导出答案的过程]\n 答案4:[A或B或C或D]]]\n\n [[题目5:[题目]\n 选项标签5:[选项标签]\n 选项内容5:[选项内容]\n 解析5：[逐步的推导出答案的过程]\n 答案5:[A或B或C或D]]]。',
    '模仿上面的问题，生成5个相似的关于{}考试的单项选择题，和这个这个题目的选项标签，选项内容，逐步的推导出答案的过程和正确答案。每个问题必须是完整且能被独立回答的。请以以下格式输出答案：[[题目1:[题目]\n 选项标签1:[选项标签]\n 选项内容1:[选项内容]\n 解析1：[逐步的推导出答案的过程]\n 答案1:[A或B或C或D]]]\n\n [[题目2:[题目]\n 选项标签2:[选项标签]\n 选项内容2:[选项内容]\n 解析2：[逐步的推导出答案的过程]\n 答案2:[A或B或C或D]]]\n\n [[题目3:[题目]\n 选项标签3:[选项标签]\n 选项内容3:[选项内容]\n 解析3：[逐步的推导出答案的过程]\n 答案3:[A或B或C或D]]]\n\n [[题目4:[题目]\n 选项标签4:[选项标签]\n 选项内容4:[选项内容]\n 解析4：[逐步的推导出答案的过程]\n 答案4:[A或B或C或D]]]\n\n [[题目5:[题目]\n 选项标签5:[选项标签]\n 选项内容5:[选项内容]\n 解析5：[逐步的推导出答案的过程]\n 答案5:[A或B或C或D]]]。',
    
    
    '请模仿上面的问题，输出5个相似的关于{}考试的单项选择题，和这个这个题目的选项标签，选项内容，逐步的推导出答案的过程和正确答案。每个问题必须是完整且能被独立回答的。请以以下格式输出答案：[[题目1:[题目]\n 选项标签1:[选项标签]\n 选项内容1:[选项内容]\n 解析1：[逐步的推导出答案的过程]\n 答案1:[A或B或C或D]]]\n\n [[题目2:[题目]\n 选项标签2:[选项标签]\n 选项内容2:[选项内容]\n 解析2：[逐步的推导出答案的过程]\n 答案2:[A或B或C或D]]]\n\n [[题目3:[题目]\n 选项标签3:[选项标签]\n 选项内容3:[选项内容]\n 解析3：[逐步的推导出答案的过程]\n 答案3:[A或B或C或D]]]\n\n [[题目4:[题目]\n 选项标签4:[选项标签]\n 选项内容4:[选项内容]\n 解析4：[逐步的推导出答案的过程]\n 答案4:[A或B或C或D]]]\n\n [[题目5:[题目]\n 选项标签5:[选项标签]\n 选项内容5:[选项内容]\n 解析5：[逐步的推导出答案的过程]\n 答案5:[A或B或C或D]]]。',
    '模仿上面的问题，输出5个相似的关于{}考试的单项选择题，和这个这个题目的选项标签，选项内容，逐步的推导出答案的过程和正确答案。每个问题必须是完整且能被独立回答的。请以以下格式输出答案：[[题目1:[题目]\n 选项标签1:[选项标签]\n 选项内容1:[选项内容]\n 解析1：[逐步的推导出答案的过程]\n 答案1:[A或B或C或D]]]\n\n [[题目2:[题目]\n 选项标签2:[选项标签]\n 选项内容2:[选项内容]\n 解析2：[逐步的推导出答案的过程]\n 答案2:[A或B或C或D]]]\n\n [[题目3:[题目]\n 选项标签3:[选项标签]\n 选项内容3:[选项内容]\n 解析3：[逐步的推导出答案的过程]\n 答案3:[A或B或C或D]]]\n\n [[题目4:[题目]\n 选项标签4:[选项标签]\n 选项内容4:[选项内容]\n 解析4：[逐步的推导出答案的过程]\n 答案4:[A或B或C或D]]]\n\n [[题目5:[题目]\n 选项标签5:[选项标签]\n 选项内容5:[选项内容]\n 解析5：[逐步的推导出答案的过程]\n 答案5:[A或B或C或D]]]。',
    
    
    '请模仿上面的问题，构造5个相似的关于{}考试的单项选择题，和这个这个题目的选项标签，选项内容，逐步的推导出答案的过程和正确答案。每个问题必须是完整且能被独立回答的。请以以下格式输出答案：[[题目1:[题目]\n 选项标签1:[选项标签]\n 选项内容1:[选项内容]\n 解析1：[逐步的推导出答案的过程]\n 答案1:[A或B或C或D]]]\n\n [[题目2:[题目]\n 选项标签2:[选项标签]\n 选项内容2:[选项内容]\n 解析2：[逐步的推导出答案的过程]\n 答案2:[A或B或C或D]]]\n\n [[题目3:[题目]\n 选项标签3:[选项标签]\n 选项内容3:[选项内容]\n 解析3：[逐步的推导出答案的过程]\n 答案3:[A或B或C或D]]]\n\n [[题目4:[题目]\n 选项标签4:[选项标签]\n 选项内容4:[选项内容]\n 解析4：[逐步的推导出答案的过程]\n 答案4:[A或B或C或D]]]\n\n [[题目5:[题目]\n 选项标签5:[选项标签]\n 选项内容5:[选项内容]\n 解析5：[逐步的推导出答案的过程]\n 答案5:[A或B或C或D]]]。',
    '模仿上面的问题，构造5个相似的关于{}考试的单项选择题，和这个这个题目的选项标签，选项内容，逐步的推导出答案的过程和正确答案。每个问题必须是完整且能被独立回答的。请以以下格式输出答案：[[题目1:[题目]\n 选项标签1:[选项标签]\n 选项内容1:[选项内容]\n 解析1：[逐步的推导出答案的过程]\n 答案1:[A或B或C或D]]]\n\n [[题目2:[题目]\n 选项标签2:[选项标签]\n 选项内容2:[选项内容]\n 解析2：[逐步的推导出答案的过程]\n 答案2:[A或B或C或D]]]\n\n [[题目3:[题目]\n 选项标签3:[选项标签]\n 选项内容3:[选项内容]\n 解析3：[逐步的推导出答案的过程]\n 答案3:[A或B或C或D]]]\n\n [[题目4:[题目]\n 选项标签4:[选项标签]\n 选项内容4:[选项内容]\n 解析4：[逐步的推导出答案的过程]\n 答案4:[A或B或C或D]]]\n\n [[题目5:[题目]\n 选项标签5:[选项标签]\n 选项内容5:[选项内容]\n 解析5：[逐步的推导出答案的过程]\n 答案5:[A或B或C或D]]]。',]

prompt_human_van=["[[Function Body]]: {implementation of the function}]\n\nFollowing the example, generate 5 similar function headers with its function body in python. Please output in the following form: [[[Function Heaser1]]:\n [[Function Body1]]: ]\n\n [[[Function Heaser2]]:\n [[Function Body2]]: ]\n\n [[[Function Heaser3]]:\n [[Function Body3]]: ]\n\n [[[Function Heaser4]]:\n [[Function Body4]]: ]\n\n [[[Function Heaser5]]:\n [[Function Body5]]: ]\n\n.",
    "[[Function Body]]: {implementation of the function}]\n\nPlease following the example, generate 5 similar function headers with its function body in python. Please output in the following form: [[[Function Heaser1]]:\n [[Function Body1]]: ]\n\n [[[Function Heaser2]]:\n [[Function Body2]]: ]\n\n [[[Function Heaser3]]:\n [[Function Body3]]: ]\n\n [[[Function Heaser4]]:\n [[Function Body4]]: ]\n\n [[[Function Heaser5]]:\n [[Function Body5]]: ]\n\n.",


    "[[Function Body]]: {implementation of the function}]\n\nFollowing the example, create 5 similar function headers with its function body in python. Please output in the following form: [[[Function Heaser1]]:\n [[Function Body1]]: ]\n\n [[[Function Heaser2]]:\n [[Function Body2]]: ]\n\n [[[Function Heaser3]]:\n [[Function Body3]]: ]\n\n [[[Function Heaser4]]:\n [[Function Body4]]: ]\n\n [[[Function Heaser5]]:\n [[Function Body5]]: ]\n\n.",
    "[[Function Body]]: {implementation of the function}]\n\nPlease following the example, create 5 similar function headers with its function body in python. Please output in the following form: [[[Function Heaser1]]:\n [[Function Body1]]: ]\n\n [[[Function Heaser2]]:\n [[Function Body2]]: ]\n\n [[[Function Heaser3]]:\n [[Function Body3]]: ]\n\n [[[Function Heaser4]]:\n [[Function Body4]]: ]\n\n [[[Function Heaser5]]:\n [[Function Body5]]: ]\n\n.",
    
    
    "[[Function Body]]: {implementation of the function}]\n\nFollowing the example, output 5 similar function headers with its function body in python. Please output in the following form: [[[Function Heaser1]]:\n [[Function Body1]]: ]\n\n [[[Function Heaser2]]:\n [[Function Body2]]: ]\n\n [[[Function Heaser3]]:\n [[Function Body3]]: ]\n\n [[[Function Heaser4]]:\n [[Function Body4]]: ]\n\n [[[Function Heaser5]]:\n [[Function Body5]]: ]\n\n.",
    "[[Function Body]]: {implementation of the function}]\n\nPlease following the example, output 5 similar function headers with its function body in python. Please output in the following form: [[[Function Heaser1]]:\n [[Function Body1]]: ]\n\n [[[Function Heaser2]]:\n [[Function Body2]]: ]\n\n [[[Function Heaser3]]:\n [[Function Body3]]: ]\n\n [[[Function Heaser4]]:\n [[Function Body4]]: ]\n\n [[[Function Heaser5]]:\n [[Function Body5]]: ]\n\n.",]

def get_demonstration_generation_prompt(dataset_name,mode='gen',scenario='van',k=0,tries=0):
    assert mode=='gen'
    if dataset_name=='GSM8k':
        if scenario=='van':
            return prompt_gsm8k_van[tries%6]
        elif scenario=='cot':
            return prompt_gsm8k_cot[tries%6]
        else:
            raise NotImplementedError
    elif dataset_name=='ARC':
        if scenario=='van':
            return prompt_arc_van[tries%6]
        elif scenario=='cot':
            return prompt_arc_cot[tries%6]
        else:
            raise NotImplementedError
    elif dataset_name=='MATH':
        if scenario=='van':
            return prompt_math_van[tries%6]
        elif scenario=='cot':
            return prompt_math_cot[tries%6]
        else:
            raise NotImplementedError
    elif dataset_name=='MMLU':
        if scenario=='van':
            return prompt_mmlu_van[tries%6]
        elif scenario=='cot':
            return prompt_mmlu_cot[tries%6]
        else:
            raise NotImplementedError
        

    elif dataset_name=='Ceval':
        if scenario=='van':
            return prompt_ceval_van[tries%6]
        elif scenario=='cot':
            return prompt_ceval_cot[tries%6]
        else:
            raise NotImplementedError


    elif dataset_name=='HumanEval':
        if scenario=='van':
            return prompt_human_van[tries%6]
        elif scenario=='cot':
            raise NotImplementedError
        else:
            raise NotImplementedError    