prompt_gsm8k_van=[
    "Please generate five similar questions with integer answer in the following form Q1:{question}\n S1:{solution}\n A1:{answer}\n\n Q2:{question}\n S2:{solution}\n A2:{answer}\n\n Q3:{question}\n S3:{solution}\n A3:{answer}\n\n Q4:{question}\n S4:{solution}\n A4:{answer}\n\n Q5:{question}\n S5:{solution}\n A5:{answer}\n\n.",
    "Generate five similar questions with integer answer in the following form Q1:{question}\n S1:{solution}\n A1:{answer}\n\n Q2:{question}\n S2:{solution}\n A2:{answer}\n\n Q3:{question}\n S3:{solution}\n A3:{answer}\n\n Q4:{question}\n S4:{solution}\n A4:{answer}\n\n Q5:{question}\n S5:{solution}\n A5:{answer}\n\n.",

    "Please create five similar questions with integer answer in the following form Q1:{question}\n S1:{solution}\n A1:{answer}\n\n Q2:{question}\n S2:{solution}\n A2:{answer}\n\n Q3:{question}\n S3:{solution}\n A3:{answer}\n\n Q4:{question}\n S4:{solution}\n A4:{answer}\n\n Q5:{question}\n S5:{solution}\n A5:{answer}\n\n.",
    "Create five similar questions with integer answer in the following form Q1:{question}\n S1:{solution}\n A1:{answer}\n\n Q2:{question}\n S2:{solution}\n A2:{answer}\n\n Q3:{question}\n S3:{solution}\n A3:{answer}\n\n Q4:{question}\n S4:{solution}\n A4:{answer}\n\n Q5:{question}\n S5:{solution}\n A5:{answer}\n\n.",


    "Please output five similar questions with integer answer in the following form Q1:{question}\n S1:{solution}\n A1:{answer}\n\n Q2:{question}\n S2:{solution}\n A2:{answer}\n\n Q3:{question}\n S3:{solution}\n A3:{answer}\n\n Q4:{question}\n S4:{solution}\n A4:{answer}\n\n Q5:{question}\n S5:{solution}\n A5:{answer}\n\n.",
    "Output five similar questions with integer answer in the following form Q1:{question}\n S1:{solution}\n A1:{answer}\n\n Q2:{question}\n S2:{solution}\n A2:{answer}\n\n Q3:{question}\n S3:{solution}\n A3:{answer}\n\n Q4:{question}\n S4:{solution}\n A4:{answer}\n\n Q5:{question}\n S5:{solution}\n A5:{answer}\n\n.",
]

prompt_gsm8k_cot=["Please generate five similar questions with step by step reasoning process and an        integer answer in the following form Q1:{question}\n S1:{solution}\n A1:{answer}\n\n Q2:{question}\n S2:{solution}\n A2:{answer}\n\n Q3:{question}\n S3:{solution}\n A3:{answer}\n\n Q4:{question}\n S4:{solution}\n A4:{answer}\n\n Q5:{question}\n S5:{solution}\n A5:{answer}\n\n.",
"Generate five similar questions with step by step reasoning process and an integer answer in the following form Q1:{question}\n S1:{solution}\n A1:{answer}\n\n Q2:{question}\n S2:{solution}\n A2:{answer}\n\n Q3:{question}\n S3:{solution}\n A3:{answer}\n\n Q4:{question}\n S4:{solution}\n A4:{answer}\n\n Q5:{question}\n S5:{solution}\n A5:{answer}\n\n."



"Please create five similar questions with step by step reasoning process and an        integer answer in the following form Q1:{question}\n S1:{solution}\n A1:{answer}\n\n Q2:{question}\n S2:{solution}\n A2:{answer}\n\n Q3:{question}\n S3:{solution}\n A3:{answer}\n\n Q4:{question}\n S4:{solution}\n A4:{answer}\n\n Q5:{question}\n S5:{solution}\n A5:{answer}\n\n.",
"Create five similar questions with step by step reasoning process and an integer answer in the following form Q1:{question}\n S1:{solution}\n A1:{answer}\n\n Q2:{question}\n S2:{solution}\n A2:{answer}\n\n Q3:{question}\n S3:{solution}\n A3:{answer}\n\n Q4:{question}\n S4:{solution}\n A4:{answer}\n\n Q5:{question}\n S5:{solution}\n A5:{answer}\n\n."


"Please output five similar questions with step by step reasoning process and an        integer answer in the following form Q1:{question}\n S1:{solution}\n A1:{answer}\n\n Q2:{question}\n S2:{solution}\n A2:{answer}\n\n Q3:{question}\n S3:{solution}\n A3:{answer}\n\n Q4:{question}\n S4:{solution}\n A4:{answer}\n\n Q5:{question}\n S5:{solution}\n A5:{answer}\n\n.",
"Output five similar questions with step by step reasoning process and an integer answer in the following form Q1:{question}\n S1:{solution}\n A1:{answer}\n\n Q2:{question}\n S2:{solution}\n A2:{answer}\n\n Q3:{question}\n S3:{solution}\n A3:{answer}\n\n Q4:{question}\n S4:{solution}\n A4:{answer}\n\n Q5:{question}\n S5:{solution}\n A5:{answer}\n\n."
                  ]


prompt_arc_van=["Follwing the above question, generate five similar multiple choice science questions with  its choice labels, choice text and an answer label in the following form [[Question1:{question}\n Label1:[choice labels]\n Text1:[choice text]\n Ans1:{answer label}]]\n\n [[Question2:{question}\n Label2:[choice labels]\n Text2:[choice text]\n Ans2:{answer label}]]\n\n [[Question3:{question}\n Label3:[choice labels]\n Text3:[choice text]\n Ans3:{answer label}]]\n\n [[Question4:{question}\n Label4:[choice labels]\n Text4:[choice text]\n Ans4:{answer label}]]\n\n [[Question5:{question}\n Label5:[choice labels]\n Text5:[choice text]\n Ans5:{answer label}]]\n\n.",
    "Please Follwing the above question, generate five similar multiple choice science questions with its choice labels, choice text and an answer label in the following form [[Question1:{question}\n Label1:[choice labels]\n Text1:[choice text]\n Ans1:{answer label}]]\n\n [[Question2:{question}\n Label2:[choice labels]\n Text2:[choice text]\n Ans2:{answer label}]]\n\n [[Question3:{question}\n Label3:[choice labels]\n Text3:[choice text]\n Ans3:{answer label}]]\n\n [[Question4:{question}\n Label4:[choice labels]\n Text4:[choice text]\n Ans4:{answer label}]]\n\n [[Question5:{question}\n Label5:[choice labels]\n Text5:[choice text]\n Ans5:{answer label}]]\n\n.",
    
    "Follwing the above question, create five similar multiple choice science questions with  its choice labels, choice text and an answer label in the following form [[Question1:{question}\n Label1:[choice labels]\n Text1:[choice text]\n Ans1:{answer label}]]\n\n [[Question2:{question}\n Label2:[choice labels]\n Text2:[choice text]\n Ans2:{answer label}]]\n\n [[Question3:{question}\n Label3:[choice labels]\n Text3:[choice text]\n Ans3:{answer label}]]\n\n [[Question4:{question}\n Label4:[choice labels]\n Text4:[choice text]\n Ans4:{answer label}]]\n\n [[Question5:{question}\n Label5:[choice labels]\n Text5:[choice text]\n Ans5:{answer label}]]\n\n.",
    "Please Follwing the above question, create five similar multiple choice science questions with its choice labels, choice text and an answer label in the following form [[Question1:{question}\n Label1:[choice labels]\n Text1:[choice text]\n Ans1:{answer label}]]\n\n [[Question2:{question}\n Label2:[choice labels]\n Text2:[choice text]\n Ans2:{answer label}]]\n\n [[Question3:{question}\n Label3:[choice labels]\n Text3:[choice text]\n Ans3:{answer label}]]\n\n [[Question4:{question}\n Label4:[choice labels]\n Text4:[choice text]\n Ans4:{answer label}]]\n\n [[Question5:{question}\n Label5:[choice labels]\n Text5:[choice text]\n Ans5:{answer label}]]\n\n.",


    "Follwing the above question, output five similar multiple choice science questions with  its choice labels, choice text and an answer label in the following form [[Question1:{question}\n Label1:[choice labels]\n Text1:[choice text]\n Ans1:{answer label}]]\n\n [[Question2:{question}\n Label2:[choice labels]\n Text2:[choice text]\n Ans2:{answer label}]]\n\n [[Question3:{question}\n Label3:[choice labels]\n Text3:[choice text]\n Ans3:{answer label}]]\n\n [[Question4:{question}\n Label4:[choice labels]\n Text4:[choice text]\n Ans4:{answer label}]]\n\n [[Question5:{question}\n Label5:[choice labels]\n Text5:[choice text]\n Ans5:{answer label}]]\n\n.",
    "Please Follwing the above question, output five similar multiple choice science questions with its choice labels, choice text and an answer label in the following form [[Question1:{question}\n Label1:[choice labels]\n Text1:[choice text]\n Ans1:{answer label}]]\n\n [[Question2:{question}\n Label2:[choice labels]\n Text2:[choice text]\n Ans2:{answer label}]]\n\n [[Question3:{question}\n Label3:[choice labels]\n Text3:[choice text]\n Ans3:{answer label}]]\n\n [[Question4:{question}\n Label4:[choice labels]\n Text4:[choice text]\n Ans4:{answer label}]]\n\n [[Question5:{question}\n Label5:[choice labels]\n Text5:[choice text]\n Ans5:{answer label}]]\n\n."]




prompt_arc_cot=["Follwing the above question, generate five similar multiple choice science questions with its choice labels, choice text, the explanation of the right answer and an answer label in the following form [[Question1:{question}\n Label1:[choice labels]\n Text1:[choice text]\n Sol1:{the explanation of the right answer}\n Ans1:{answer label}]]\n\n [[Question2:{question}\n Label2:[choice labels]\n Text2:[choice text]\n Sol2:{the explanation of the right answer}\n Ans2:{answer label}]]\n\n [[Question3:{question}\n Label3:[choice labels]\n Text3:[choice text]\n Sol3:{the explanation of the right answer}\n Ans3:{answer label}]]\n\n [[Question4:{question}\n Label4:[choice labels]\n Text4:[choice text]\n Sol4:{the explanation of the right answer}\n Ans4:{answer label}]]\n\n [[Question5:{question}\n Label5:[choice labels]\n Text5:[choice text]\n Sol5:{the explanation of the right answer}\n Ans5:{answer label}]]\n\n  [[Question6:{question}\n Label6:[choice labels]\n Text6:[choice text]\n Sol6:{the explanation of the right answer}\n Ans6:{answer label}]]\n\n [[Question7:{question}\n Label7:[choice labels]\n Text7:[choice text]\n Sol7:{the explanation of the right answer}\n Ans7:{answer label}]]\n\n [[Question8:{question}\n Label8:[choice labels]\n Text8:[choice text]\n Sol8:{the explanation of the right answer}\n Ans8:{answer label}]]\n\n [[Question9:{question}\n Label9:[choice labels]\n Text9:[choice text]\n Sol9:{the explanation of the right answer}\n Ans9:{answer label}]]\n\n [[Question10:{question}\n Label10:[choice labels]\n Text10:[choice text]\n Sol10:{the explanation of the right answer}\n Ans10:{answer label}]]\n\n.",
    "Please follwing the above question, generate five similar multiple choice science questions with its choice labels, choice text, the explanation of the right answer and an answer label in the following form [[Question1:{question}\n Label1:[choice labels]\n Text1:[choice text]\n Sol1:{the explanation of the right answer}\n Ans1:{answer label}]]\n\n [[Question2:{question}\n Label2:[choice labels]\n Text2:[choice text]\n Sol2:{the explanation of the right answer}\n Ans2:{answer label}]]\n\n [[Question3:{question}\n Label3:[choice labels]\n Text3:[choice text]\n Sol3:{the explanation of the right answer}\n Ans3:{answer label}]]\n\n [[Question4:{question}\n Label4:[choice labels]\n Text4:[choice text]\n Sol4:{the explanation of the right answer}\n Ans4:{answer label}]]\n\n [[Question5:{question}\n Label5:[choice labels]\n Text5:[choice text]\n Sol5:{the explanation of the right answer}\n Ans5:{answer label}]]\n\n  [[Question6:{question}\n Label6:[choice labels]\n Text6:[choice text]\n Sol6:{the explanation of the right answer}\n Ans6:{answer label}]]\n\n [[Question7:{question}\n Label7:[choice labels]\n Text7:[choice text]\n Sol7:{the explanation of the right answer}\n Ans7:{answer label}]]\n\n [[Question8:{question}\n Label8:[choice labels]\n Text8:[choice text]\n Sol8:{the explanation of the right answer}\n Ans8:{answer label}]]\n\n [[Question9:{question}\n Label9:[choice labels]\n Text9:[choice text]\n Sol9:{the explanation of the right answer}\n Ans9:{answer label}]]\n\n [[Question10:{question}\n Label10:[choice labels]\n Text10:[choice text]\n Sol10:{the explanation of the right answer}\n Ans10:{answer label}]]\n\n.",
    
    
    "Follwing the above question, create five similar multiple choice science questions with its choice labels, choice text, the explanation of the right answer and an answer label in the following form [[Question1:{question}\n Label1:[choice labels]\n Text1:[choice text]\n Sol1:{the explanation of the right answer}\n Ans1:{answer label}]]\n\n [[Question2:{question}\n Label2:[choice labels]\n Text2:[choice text]\n Sol2:{the explanation of the right answer}\n Ans2:{answer label}]]\n\n [[Question3:{question}\n Label3:[choice labels]\n Text3:[choice text]\n Sol3:{the explanation of the right answer}\n Ans3:{answer label}]]\n\n [[Question4:{question}\n Label4:[choice labels]\n Text4:[choice text]\n Sol4:{the explanation of the right answer}\n Ans4:{answer label}]]\n\n [[Question5:{question}\n Label5:[choice labels]\n Text5:[choice text]\n Sol5:{the explanation of the right answer}\n Ans5:{answer label}]]\n\n  [[Question6:{question}\n Label6:[choice labels]\n Text6:[choice text]\n Sol6:{the explanation of the right answer}\n Ans6:{answer label}]]\n\n [[Question7:{question}\n Label7:[choice labels]\n Text7:[choice text]\n Sol7:{the explanation of the right answer}\n Ans7:{answer label}]]\n\n [[Question8:{question}\n Label8:[choice labels]\n Text8:[choice text]\n Sol8:{the explanation of the right answer}\n Ans8:{answer label}]]\n\n [[Question9:{question}\n Label9:[choice labels]\n Text9:[choice text]\n Sol9:{the explanation of the right answer}\n Ans9:{answer label}]]\n\n [[Question10:{question}\n Label10:[choice labels]\n Text10:[choice text]\n Sol10:{the explanation of the right answer}\n Ans10:{answer label}]]\n\n.",
    "Please follwing the above question, create five similar multiple choice science questions with its choice labels, choice text, the explanation of the right answer and an answer label in the following form [[Question1:{question}\n Label1:[choice labels]\n Text1:[choice text]\n Sol1:{the explanation of the right answer}\n Ans1:{answer label}]]\n\n [[Question2:{question}\n Label2:[choice labels]\n Text2:[choice text]\n Sol2:{the explanation of the right answer}\n Ans2:{answer label}]]\n\n [[Question3:{question}\n Label3:[choice labels]\n Text3:[choice text]\n Sol3:{the explanation of the right answer}\n Ans3:{answer label}]]\n\n [[Question4:{question}\n Label4:[choice labels]\n Text4:[choice text]\n Sol4:{the explanation of the right answer}\n Ans4:{answer label}]]\n\n [[Question5:{question}\n Label5:[choice labels]\n Text5:[choice text]\n Sol5:{the explanation of the right answer}\n Ans5:{answer label}]]\n\n  [[Question6:{question}\n Label6:[choice labels]\n Text6:[choice text]\n Sol6:{the explanation of the right answer}\n Ans6:{answer label}]]\n\n [[Question7:{question}\n Label7:[choice labels]\n Text7:[choice text]\n Sol7:{the explanation of the right answer}\n Ans7:{answer label}]]\n\n [[Question8:{question}\n Label8:[choice labels]\n Text8:[choice text]\n Sol8:{the explanation of the right answer}\n Ans8:{answer label}]]\n\n [[Question9:{question}\n Label9:[choice labels]\n Text9:[choice text]\n Sol9:{the explanation of the right answer}\n Ans9:{answer label}]]\n\n [[Question10:{question}\n Label10:[choice labels]\n Text10:[choice text]\n Sol10:{the explanation of the right answer}\n Ans10:{answer label}]]\n\n.",
    
    
    
    "Follwing the above question, output five similar multiple choice science questions with its choice labels, choice text, the explanation of the right answer and an answer label in the following form [[Question1:{question}\n Label1:[choice labels]\n Text1:[choice text]\n Sol1:{the explanation of the right answer}\n Ans1:{answer label}]]\n\n [[Question2:{question}\n Label2:[choice labels]\n Text2:[choice text]\n Sol2:{the explanation of the right answer}\n Ans2:{answer label}]]\n\n [[Question3:{question}\n Label3:[choice labels]\n Text3:[choice text]\n Sol3:{the explanation of the right answer}\n Ans3:{answer label}]]\n\n [[Question4:{question}\n Label4:[choice labels]\n Text4:[choice text]\n Sol4:{the explanation of the right answer}\n Ans4:{answer label}]]\n\n [[Question5:{question}\n Label5:[choice labels]\n Text5:[choice text]\n Sol5:{the explanation of the right answer}\n Ans5:{answer label}]]\n\n  [[Question6:{question}\n Label6:[choice labels]\n Text6:[choice text]\n Sol6:{the explanation of the right answer}\n Ans6:{answer label}]]\n\n [[Question7:{question}\n Label7:[choice labels]\n Text7:[choice text]\n Sol7:{the explanation of the right answer}\n Ans7:{answer label}]]\n\n [[Question8:{question}\n Label8:[choice labels]\n Text8:[choice text]\n Sol8:{the explanation of the right answer}\n Ans8:{answer label}]]\n\n [[Question9:{question}\n Label9:[choice labels]\n Text9:[choice text]\n Sol9:{the explanation of the right answer}\n Ans9:{answer label}]]\n\n [[Question10:{question}\n Label10:[choice labels]\n Text10:[choice text]\n Sol10:{the explanation of the right answer}\n Ans10:{answer label}]]\n\n.",
    "Please follwing the above question, output five similar multiple choice science questions with its choice labels, choice text, the explanation of the right answer and an answer label in the following form [[Question1:{question}\n Label1:[choice labels]\n Text1:[choice text]\n Sol1:{the explanation of the right answer}\n Ans1:{answer label}]]\n\n [[Question2:{question}\n Label2:[choice labels]\n Text2:[choice text]\n Sol2:{the explanation of the right answer}\n Ans2:{answer label}]]\n\n [[Question3:{question}\n Label3:[choice labels]\n Text3:[choice text]\n Sol3:{the explanation of the right answer}\n Ans3:{answer label}]]\n\n [[Question4:{question}\n Label4:[choice labels]\n Text4:[choice text]\n Sol4:{the explanation of the right answer}\n Ans4:{answer label}]]\n\n [[Question5:{question}\n Label5:[choice labels]\n Text5:[choice text]\n Sol5:{the explanation of the right answer}\n Ans5:{answer label}]]\n\n  [[Question6:{question}\n Label6:[choice labels]\n Text6:[choice text]\n Sol6:{the explanation of the right answer}\n Ans6:{answer label}]]\n\n [[Question7:{question}\n Label7:[choice labels]\n Text7:[choice text]\n Sol7:{the explanation of the right answer}\n Ans7:{answer label}]]\n\n [[Question8:{question}\n Label8:[choice labels]\n Text8:[choice text]\n Sol8:{the explanation of the right answer}\n Ans8:{answer label}]]\n\n [[Question9:{question}\n Label9:[choice labels]\n Text9:[choice text]\n Sol9:{the explanation of the right answer}\n Ans9:{answer label}]]\n\n [[Question10:{question}\n Label10:[choice labels]\n Text10:[choice text]\n Sol10:{the explanation of the right answer}\n Ans10:{answer label}]]\n\n."]



prompt_math_van=[
    '\nPlease follwing the above question, generate five similar questions with its answer in Latex. Please output in the following form [[Question1:{question}\n Answer1:$answer in Latex$]]\n\n [[Question2:{question}\n Answer2:$answer in Latex$]]\n\n [[Question3:{question}\n Answer3:$answer in Latex$]]\n\n [[Question4:{question}\n Answer4:$answer in Latex$]]\n\n [[Question5:{question}\n Answer5:$answer in Latex$]]\n\n.'
    '\nFollwing the above question, generate five similar questions with its answer in Latex. Please output in the following form [[Question1:{question}\n Answer1:$answer in Latex$]]\n\n [[Question2:{question}\n Answer2:$answer in Latex$]]\n\n [[Question3:{question}\n Answer3:$answer in Latex$]]\n\n [[Question4:{question}\n Answer4:$answer in Latex$]]\n\n [[Question5:{question}\n Answer5:$answer in Latex$]]\n\n.',


    '\nPlease follwing the above question, create five similar questions with its answer in Latex. Please output in the following form [[Question1:{question}\n Answer1:$answer in Latex$]]\n\n [[Question2:{question}\n Answer2:$answer in Latex$]]\n\n [[Question3:{question}\n Answer3:$answer in Latex$]]\n\n [[Question4:{question}\n Answer4:$answer in Latex$]]\n\n [[Question5:{question}\n Answer5:$answer in Latex$]]\n\n.'
    '\nFollwing the above question, create five similar questions with its answer in Latex. Please output in the following form [[Question1:{question}\n Answer1:$answer in Latex$]]\n\n [[Question2:{question}\n Answer2:$answer in Latex$]]\n\n [[Question3:{question}\n Answer3:$answer in Latex$]]\n\n [[Question4:{question}\n Answer4:$answer in Latex$]]\n\n [[Question5:{question}\n Answer5:$answer in Latex$]]\n\n.',


    '\nPlease follwing the above question, output five similar questions with its answer in Latex. Please output in the following form [[Question1:{question}\n Answer1:$answer in Latex$]]\n\n [[Question2:{question}\n Answer2:$answer in Latex$]]\n\n [[Question3:{question}\n Answer3:$answer in Latex$]]\n\n [[Question4:{question}\n Answer4:$answer in Latex$]]\n\n [[Question5:{question}\n Answer5:$answer in Latex$]]\n\n.'
    '\nFollwing the above question, output five similar questions with its answer in Latex. Please output in the following form [[Question1:{question}\n Answer1:$answer in Latex$]]\n\n [[Question2:{question}\n Answer2:$answer in Latex$]]\n\n [[Question3:{question}\n Answer3:$answer in Latex$]]\n\n [[Question4:{question}\n Answer4:$answer in Latex$]]\n\n [[Question5:{question}\n Answer5:$answer in Latex$]]\n\n.'
]


prompt_math_cot=['\nPlease follwing the above question, generate 5 similar questions with its step by step solution and answer in Latex. Please output in the following form [[Question1:{question}\n Sol1:[step by step solution]\n Answer1:$answer in Latex$]]\n\n [[Question2:{question}\n Sol2:[step by step solution]\n Answer2:$answer in Latex$]]\n\n [[Question3:{question}\n Sol3:[step by step solution]\n Answer3:$answer in Latex$]]\n\n [[Question4:{question}\n Sol4:[step by step solution]\n Answer4:$answer in Latex$]]\n\n [[Question5:{question}\n Sol5:[step by step solution]\n Answer5:$answer in Latex$]]\n\n.',
    '\nPlease follwing the above question, generate 5 similar questions with its step by step solution and answer in Latex. Please output in the following form [[Question1:{question}\n Sol1:[step by step solution]\n Answer1:$answer in Latex$]]\n\n [[Question2:{question}\n Sol2:[step by step solution]\n Answer2:$answer in Latex$]]\n\n [[Question3:{question}\n Sol3:[step by step solution]\n Answer3:$answer in Latex$]]\n\n [[Question4:{question}\n Sol4:[step by step solution]\n Answer4:$answer in Latex$]]\n\n [[Question5:{question}\n Sol5:[step by step solution]\n Answer5:$answer in Latex$]]\n\n.',
    
    
    
    '\nPlease follwing the above question, create 5 similar questions with its step by step solution and answer in Latex. Please output in the following form [[Question1:{question}\n Sol1:[step by step solution]\n Answer1:$answer in Latex$]]\n\n [[Question2:{question}\n Sol2:[step by step solution]\n Answer2:$answer in Latex$]]\n\n [[Question3:{question}\n Sol3:[step by step solution]\n Answer3:$answer in Latex$]]\n\n [[Question4:{question}\n Sol4:[step by step solution]\n Answer4:$answer in Latex$]]\n\n [[Question5:{question}\n Sol5:[step by step solution]\n Answer5:$answer in Latex$]]\n\n.',
    '\nPlease follwing the above question, create 5 similar questions with its step by step solution and answer in Latex. Please output in the following form [[Question1:{question}\n Sol1:[step by step solution]\n Answer1:$answer in Latex$]]\n\n [[Question2:{question}\n Sol2:[step by step solution]\n Answer2:$answer in Latex$]]\n\n [[Question3:{question}\n Sol3:[step by step solution]\n Answer3:$answer in Latex$]]\n\n [[Question4:{question}\n Sol4:[step by step solution]\n Answer4:$answer in Latex$]]\n\n [[Question5:{question}\n Sol5:[step by step solution]\n Answer5:$answer in Latex$]]\n\n.',
    
    
    '\nPlease follwing the above question, output 5 similar questions with its step by step solution and answer in Latex. Please output in the following form [[Question1:{question}\n Sol1:[step by step solution]\n Answer1:$answer in Latex$]]\n\n [[Question2:{question}\n Sol2:[step by step solution]\n Answer2:$answer in Latex$]]\n\n [[Question3:{question}\n Sol3:[step by step solution]\n Answer3:$answer in Latex$]]\n\n [[Question4:{question}\n Sol4:[step by step solution]\n Answer4:$answer in Latex$]]\n\n [[Question5:{question}\n Sol5:[step by step solution]\n Answer5:$answer in Latex$]]\n\n.',
    '\nPlease follwing the above question, output 5 similar questions with its step by step solution and answer in Latex. Please output in the following form [[Question1:{question}\n Sol1:[step by step solution]\n Answer1:$answer in Latex$]]\n\n [[Question2:{question}\n Sol2:[step by step solution]\n Answer2:$answer in Latex$]]\n\n [[Question3:{question}\n Sol3:[step by step solution]\n Answer3:$answer in Latex$]]\n\n [[Question4:{question}\n Sol4:[step by step solution]\n Answer4:$answer in Latex$]]\n\n [[Question5:{question}\n Sol5:[step by step solution]\n Answer5:$answer in Latex$]]\n\n.']






def get_demonstration_generation_prompt(dataset_name,mode='gen',scenario='van',k=0,tries=0):
    assert mode=='gen'
    if dataset_name=='GSM8k':
        if scenario=='van':
            return prompt_gsm8k_van[tries%6]
        elif scenario=='cot':
            return prompt_gsm8k_cot[tries%6]
        else:
            raise NotImplementedError
    elif dataset_name=='ARC':
        if scenario=='van':
            return prompt_arc_van[tries%6]
        elif scenario=='cot':
            return prompt_arc_cot[tries%6]
        else:
            raise NotImplementedError
    elif dataset_name=='MATH':
        if scenario=='van':
            return prompt_math_van[tries%6]
        elif scenario=='cot':
            return prompt_math_cot[tries%6]
        else:
            raise NotImplementedError
    elif dataset_name=='MMLU':



    